version: '3.4'

services:
  yahoo.variacao.ativo.api:
    image: ${DOCKER_REGISTRY-}yahoovariacaoativoapi
    build:
      context: .
      dockerfile: Yahoo.Variacao.Ativo.API/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - 'db'
      - 'flyway'
  flyway:
    image: flyway/flyway
    command: -url="jdbc:sqlserver://db;databaseName=master" -user=sa -password=SenhaPadrao -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "SenhaPadrao"
        ACCEPT_EULA: "Y"
 
